remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Security
description: A short description of your site's purpose
show_downloads: false
collections:
  blog_categories:
    output: true
    permalink: /blog/category/:name/
